export const CITY_NAMES = [
  'Kilgate',
  'Dustfair',
  'Deadbreak',
  'Greenscar',
  'Silkbreak',
  'Cragborough',
  'Greenfrost',
  'Snowhelm',
  'Midacre',
  'Fearvalley',
  'Shadekeep',
  'Steamvein',
  'Tradespell',
  'Westshell',
  'Northreach',
  'Fairrun',
  'Oakenshire',
  'Windhall',
  'Redfrost',
  'Glimmerborn',
  'Redwick',
  'Quicktown',
  'Stormgulf',
  'Deepgarde',
  'Craghall',
  'Lakeharbor',
  'Bonehaven',
  'Greenhand',
  'Newshear',
  'Puremere',
  'Cloudwell',
  'Oceanmoor',
  'Rosehand',
  'Boulderward',
  'Sleettide',
  'Bleakpost',
  'Limehallow',
  'Whalehall',
  'Roguehelm',
  'Knightcoast',
  'Smoothcoast',
  'Ebonwell',
  'Basinfall',
  'Winterview',
  'Cursetide',
  'Ravenborough',
  'Boulderwind',
  'Steelvale',
  'Beachbury',
  'Springfront',
]

export const districtTypes = [
  {
    id: 'center',
    label: 'City Center',
    tasks: [{ id: 'scavenge' }],
  },
  { id: 'barracks', label: 'Encampment', tasks: [{ id: 'hunt' }] },
  {
    id: 'industry',
    label: 'Industrial Zone',
    tasks: [{ id: 'mine' }, { id: 'chop' }],
  },
  { id: 'church', label: 'Holy Site', tasks: [{ id: 'pray' }] },
  { id: 'campus', label: 'Campus', tasks: [{ id: 'study' }] },
  { id: 'market', label: 'Commercial Hub', tasks: [{ id: 'trade' }] },
  { id: 'theatre', label: 'Theatre Square', tasks: [{ id: 'perform' }] },
]

export const tasks = [
  {
    id: 'scavenge',
    duration: 1,
    effects: [
      { id: 'food', value: [1, 4] },
      { id: 'wood', value: [0, 0, 0, 0.1, 0.2] },
    ],
  },
  {
    id: 'chop',
    biome: ['forest'],
    duration: 1,
    effects: [{ id: 'wood', value: 1 }],
  },
  {
    id: 'farm',
    biome: ['plain'],
    duration: 1,
    effects: [{ id: 'food', value: 10 }],
  },
  {
    id: 'mine',
    biome: ['mountain'],
    duration: 1,
    effects: [{ id: 'stone', value: 1 }],
  },
  { id: 'pray', duration: 1, effects: [{ id: 'faith', value: 1 }] },
  { id: 'hunt', duration: 1, effects: [{ id: 'fur', value: 1 }] },
  { id: 'trade', duration: 1, effects: [{ id: 'gold', value: 1 }] },
  { id: 'perform', duration: 1, effects: [{ id: 'culture', value: 1 }] },
  { id: 'study', duration: 1, effects: [{ id: 'science', value: 1 }] },
  1,
]
